const NEW_MODULE_REQUEST = 'NEW_MODULE_REQUEST'

const NEW_MODULE_SUCCESS = 'NEW_MODULE_SUCCESS'

const NEW_MODULE_FAILURE = 'NEW_MODULE_FAILURE'

const GET_MODULE_REQUEST = 'GET_MODULE_REQUEST'

const GET_MODULE_SUCCESS = 'GET_MODULE_SUCCESS'

const GET_MODULE_FAILURE = 'GET_MODULE_FAILURE'

const UPDATE_MODULE_REQUEST = 'UPDATE_MODULE_REQUEST'

const UPDATE_MODULE_SUCCESS = 'UPDATE_MODULE_SUCCESS'

const UPDATE_MODULE_FAILURE = 'UPDATE_MODULE_FAILURE'

const DELETE_MODULE_REQUEST = 'DELETE_MODULE_REQUEST'

const DELETE_MODULE_SUCCESS = 'DELETE_MODULE_SUCCESS'

const DELETE_MODULE_FAILURE = 'DELETE_MODULE_FAILURE'

const SEARCH_MODULES_REQUEST = 'SEARCH_MODULES_REQUEST'

const SEARCH_MODULES_SUCCESS = 'SEARCH_MODULES_SUCCESS'

const SEARCH_MODULES_FAILURE = 'SEARCH_MODULES_FAILURE'

const initialState = {
    components: {
        items: {
            modules: [],
            
        }
    }
}